version: '3.7'

services:
    mysql-db:
        image: mysql:latest
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: business
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        ports:
            - '3307:3306'
        volumes:
            - mysql-data:/var/lib/mysql
            - ./src/database/create-database.sql:/docker-entrypoint-initdb.d/dump.sql
    otel-collector:
        image: otel/opentelemetry-collector-contrib:latest
        command: ['--config=/etc/otel-collector-config.yaml']
        volumes:
            - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
            - '4317:4317' # OTLP gRPC
            - '4318:4318' # OTLP HTTP
        depends_on:
            - tempo
            - loki
            - prometheus

    prometheus:
        image: prom/prometheus
        volumes:
            - ./prometheus.yml:/etc/prometheus/prometheus.yml
        command:
            - --config.file=/etc/prometheus/prometheus.yml
        ports:
            - '9090:9090'

    grafana:
        image: grafana/grafana-oss
        ports:
            - '3000:3000'
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=admin
        volumes:
            - grafana-storage:/var/lib/grafana
        depends_on:
            - prometheus
            - tempo
            - loki

    tempo:
        image: grafana/tempo:latest
        command: ['-config.file=/etc/tempo.yaml']
        volumes:
            - ./tempo.yaml:/etc/tempo.yaml
        ports:
            - '14268:14268' # jaeger ingest
            - '3200:3200' # tempo
            - '9095:9095' # tempo grpc
            - '4319:4317' # otlp grpc
            - '4320:4318' # otlp http
            - '9411:9411' # zipkin

    loki:
        image: grafana/loki:latest
        command: -config.file=/etc/loki/local-config.yaml
        ports:
            - '3100:3100'

volumes:
    mysql-data:
    grafana-storage:
