receivers:
    otlp:
        protocols:
            grpc:
                endpoint: 0.0.0.0:4317
            http:
                endpoint: 0.0.0.0:4318
exporters:
    debug:
        verbosity: detailed
    loki:
        endpoint: 'http://loki:3100/loki/api/v1/push'
    prometheus:
        endpoint: '0.0.0.0:8889'
    # datadog:
    #     api:
    #         key: '<DD_API_KEY>'
    #         site: 'us3.datadoghq.com'
    otlp/tempo:
        endpoint: tempo:4317
        tls:
            insecure: true
processors:
    batch:
        timeout: 5s
        send_batch_size: 1024
        send_batch_max_size: 2048
service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [otlp/tempo]
        metrics:
            receivers: [otlp]
            processors: [batch]
            exporters: [prometheus, debug]
        logs:
            receivers: [otlp]
            processors: [batch]
            exporters: [loki, debug]
    telemetry:
        logs:
            level: 'debug'
